from sqlalchemy import Column, String, Integer, DateTime, ForeignKey, func
from sqlalchemy.orm import relationship
import uuid

from app.core.database import Base


class AffiliateLink(Base):
    """A tracking link generated by a creator.

    link_type == "single" → one product, customer is redirected straight to the
    BeautyBarn product page. link_type == "bundle" → two or more products, customer
    lands on the branded multi-product landing page (SOW 3.3).
    """

    __tablename__ = "affiliate_links"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    code = Column(String, unique=True, nullable=False, index=True)
    creator_id = Column(String, ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    link_type = Column(String, nullable=False)  # single | bundle
    title = Column(String, nullable=True)       # optional label for bundles

    total_clicks = Column(Integer, default=0, nullable=False)
    total_orders = Column(Integer, default=0, nullable=False)
    total_commission = Column(Integer, default=0, nullable=False)

    created_at = Column(DateTime(timezone=True), server_default=func.now())

    items = relationship(
        "AffiliateLinkItem",
        back_populates="link",
        cascade="all, delete-orphan",
        lazy="selectin",
    )


class AffiliateLinkItem(Base):
    """One product inside a link. Per-product rows give per-product attribution
    on the bundle landing page (SOW 3.3 #3)."""

    __tablename__ = "affiliate_link_items"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    link_id = Column(String, ForeignKey("affiliate_links.id", ondelete="CASCADE"), nullable=False, index=True)
    product_id = Column(String, ForeignKey("products.id", ondelete="CASCADE"), nullable=False, index=True)
    clicks = Column(Integer, default=0, nullable=False)

    link = relationship("AffiliateLink", back_populates="items")
    product = relationship("Product", lazy="selectin")


class LinkClick(Base):
    """Immutable click event, written before any redirect (SOW tracking)."""

    __tablename__ = "link_clicks"

    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    link_id = Column(String, ForeignKey("affiliate_links.id", ondelete="CASCADE"), nullable=False, index=True)
    code = Column(String, nullable=False, index=True)      # affiliate id / link code
    creator_id = Column(String, nullable=False, index=True)  # influencer id
    product_id = Column(String, nullable=True, index=True)   # null for a bundle page open
    bundle_id = Column(String, nullable=True, index=True)    # link id when bundle
    source = Column(String, nullable=True)                   # instagram | youtube | direct ...
    referrer = Column(String, nullable=True)
    user_agent = Column(String, nullable=True)
    ip_address = Column(String, nullable=True)
    clicked_at = Column(DateTime(timezone=True), server_default=func.now(), index=True)
